version: "3.9"
name: tests_using_allin1_container

  # Goal: a compose equivalent of:
  # "docker run -p 9030:9030 -p 8030:8030 -p 8040:8040 -itd --name quickstart starrocks/allin1-ubuntu"

networks:
  allin1:

services:
  allin1:
    image: starrocks/allin1-ubuntu:3.2-latest
    hostname: fe
    container_name: quickstart
    ports:
      - 9030:9030
      - 8030:8030
      - 8040:8040
    user: root

    healthcheck:
      test: 'mysql -u root -h fe -P 9030 -e "show backends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - allin1

  # This section is commented out as the ports of the allin1 need to be
  #  made available to the host env and the tests need to run from the
  #  host. Leaving this in the file as I will need it for other
  #  situations and need a reference.
  # test-harness:
  #  extends:
  #    file: ./test-harness-docker-compose.yml
  #    service: test-harness
  #  command: ash
  #  tty: true
  #  networks:
  #    - allin1
