version: "3.9"
services:

  starrocks-fe:
    image: starrocks/fe-ubuntu:3.2-latest
    hostname: fe
    container_name: fe
    user: root

    command:
      /opt/starrocks/fe/bin/start_fe.sh
    ports:
      - 8030:8030
      - 9020:9020
      - 9030:9030
    healthcheck:
      test: 'mysql -u root -h fe -P 9030 -e "show frontends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3

  starrocks-be:
    image: starrocks/be-ubuntu:3.2-latest

    command:
      - /bin/bash
      - -c
      - |
        sleep 15s; mysql --connect-timeout 2 -h fe -P 9030 -u root -e "alter system add backend \"be:9050\";"
        /opt/starrocks/be/bin/start_be.sh
    hostname: be
    container_name: be
    user: root
    depends_on:
      - starrocks-fe
    ports:
      - 8040:8040
    healthcheck:
      test: 'mysql -u root -h fe -P 9030 -e "show backends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
