version: "3.9"
services:

  test-harness:
    image: ginkgo
    hostname: ginkgo
    container_name: ginkgo
    user: root
    command: ash
    tty: true
    build:
      context: ci
      dockerfile: ginkgo.Dockerfile
