version: "3.9"
services:

  test-harness:
    image: ginkgo
    hostname: ginkgo
    container_name: ginkgo
    environment:
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
    user: root
    build:
      context: ci
      dockerfile: ginkgo.Dockerfile
    networks:
      mynet: {}

networks:
  mynet:
    external: true
    name: ${network}
