name: Test the docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo as this CI needs:
      # - the compose file for StarRocks
      # - the Ginkgo/Gomega test system
      - uses: actions/checkout@v3

      # This compose action will deploy StarRocks
      # in Docker using the compose file in this repo
      - name: Start StarRocks
        uses: isbang/compose-action@v1.4.1
        with:
          down-flags: "--volumes"
          services: |
            db

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Test
        run: ginkgo -vv
