name: Test with Shared Data

on:
  schedule:
    - cron: "5 9 * * 1"
  push:
    branches: [ main ]
    paths:
      - 'ci/**/quickstart/shared_data/*'
      - '.github/workflows/test_with_shared_data.yml'
      - 'quickstart_shared_data_test.go'
      - 'helper.go'
  pull_request:
    branches: [ main ]
    paths:
      - 'ci/**/quickstart/shared_data/*'
      - '.github/workflows/test_with_shared_data.yml'
      - 'quickstart_shared_data_test.go'
      - 'helper.go'

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo as this CI needs:
      # - the compose file for StarRocks and Ginkgo/Gomega
      - name: Checkout Test repo
        uses: actions/checkout@v4
          #with:
          #path: testing

      # Build the test harness container (Golnag/Ginkgo/Gomega)
      - name: Build Ginkgo container
        run: |
          curl -o shared_data-compose.yml \
            https://raw.githubusercontent.com/StarRocks/demo/master/documentation-samples/quickstart/docker-compose.yml
          docker compose -f shared_data-compose.yml -f test-harness-docker-compose.yml -f minio-fix-compose.yml build

      - name: Start StarRocks and MinIO
        run: |
          docker compose \
            -f shared_data-compose.yml \
            -f test-harness-docker-compose.yml \
            -f minio-fix-compose.yml \
            up --detach --wait --wait-timeout 100

      # Any tests that will run against the StarRocks env would be 
      # launched in steps like this one. Make sure to reset the 
      # StarRocks environment after each run (remove any tables
      # and databases created, and reset any settings to the default)
      #
      # The ginkgo command uses `--focus-file` to run only the one test
      # file.
      - name: Test; Shared Data SQL test
        if: always()
        run: docker compose -f shared_data-compose.yml -f test-harness-docker-compose.yml -f minio-fix-compose.yml exec -e SR_FE_HOST='starrocks-fe' test-harness ginkgo -v --focus-file=./quickstart_shared_data_test.go
