name: Test Basic Quickstart
on:
  workflow_dispatch:
  #schedule:
    #- cron: "5 9 * * 1"
  #push:
    #branches: [ main ]
    #paths:
      #- 'ci/**/quickstart/basic/*'
      #- '.github/workflows/test_with_allin1.yml'
      #- 'allin1-docker-compose.yml'
      #- 'quickstart_basic_test.go'
      #- 'helper.go'
      #- 'ginkgo.Dockerfile'
  #pull_request:
    #branches: [ main ]
    #paths:
      #- 'ci/**/quickstart/basic/*'
      #- '.github/workflows/test_with_allin1.yml'
      #- 'allin1-docker-compose.yml'
      #- 'quickstart_basic_test.go'
      #- 'helper.go'
      #- 'ginkgo.Dockerfile'

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo as this CI needs:
      # - the compose file for StarRocks and Ginkgo/Gomega
      - uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: 'ci/go.mod'

      - name: Install ginkgo
        run: |
          version=$(cat go.mod| grep "ginkgo/v2" | awk '{print $2}')
          go install -v github.com/onsi/ginkgo/v2/ginkgo@$version
        working-directory: ./ci

      - name: Start StarRocks
        run: docker compose -f allin1-docker-compose.yml up --detach --wait --wait-timeout 60

      # Any tests that will run against the StarRocks env would be 
      # launched in steps like this one. Make sure to reset the 
      # StarRocks environment after each run (remove any tables
      # and databases created, and reset any settings to the default)
      #
      # The ginkgo command uses `--focus-file` to run only the one test
      # file.
      - name: Test; Basic Quick Start
        if: always()
        env:
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          SR_FE_HOST: 'localhost'
        run: ginkgo -v --focus-file=./quickstart_basic_test.go
        working-directory: ./ci

      # Add more tests here if there are other things
      # that should run against allin1
